#!/bin/bash

fiona() {
- this should execute any word with a period or comma in the middle, and print
- anything else.

while read LINE
  do 
  echo $LINE | xargs -n1 | fiona.grep ".\.." RED
  done
}

fiona.grep() {

echo "$1 ....."

grep "$1" >/dev/null
  if [[ $? -eq 0 ]]
    then
       echo "...... $2 ......"
  fi

}

# alp creates a function for each option defined
alp ()
{
- alp $1 $2
T=/tmp/$$
echo "$1.$2() { $1 $2; }" > $T
source $T
#cat $T
rm $T
}
