#!/bin/bash

fiona() {
- this should execute any word with a period or comma in the middle, and print
- anything else.

while read LINE
  do 
  echo $LINE | xargs -n1 | fiona.grep ".\.." RED
  done
}

fiona.grep() {

echo "$1 ....."

grep "$1" >/dev/null
  if [[ $? -eq 0 ]]
    then
       echo "...... $2 ......"
  fi

}

# alp creates a function for each option defined
alp ()
{
COMMAND=$1
shift 1
while [[ "$*" ]]
do
  - alp $COMMAND $1
  T=/tmp/$$
  echo "$COMMAND.$1() { $COMMAND $1; }" >> $T
  shift 1
done
  source $T
  - cat $T
  rm $T
}
