#!/bin/bash
## Sbshell version 3.1 

#  Covered by Apache License
#  12/14/2015
#
#

#if [[ $1 != "quiet" ]]

#then
#echo "Copyright 2015 Secret Beach Solutions

#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at

 #   http://www.apache.org/licenses/LICENSE-2.0

#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License."
#fi

source $SB_HOME/alp

color() { 
- color Changed the color in the shell or web version
- color Possible colors are white,bold,underline,error,red,green,yellow,blue,purple,aqua

	if [ -n $1 ]
	then
    case $1 in
        white)
            FG='00m'
        ;;
        bold)
            FG='01m'
        ;;
        underline)
            FG='04m'
        ;;
        error)
            FG='31m'
        ;;
        red)
            FG='31m'
        ;;
        green)
            FG='32m'
        ;;
        yellow)
            FG='33m'
        ;;
        blue)
            FG='34m'
        ;;
        purple)
            FG='35m'
        ;;
        aqua)
            FG='36m'
  			;;
    esac;

#    echo -n -e
     printf "\033[$FG"
	else 
		sb.help color
	fi

}

for X in white bold underline error red green yellow blue purple aqua
  do
  alp color $X
  done

