#!/bin/bash
## Sbshell version 3.1 

#  Covered by Apache License
#  12/14/2015
#
#

#echo "Copyright 2015 Secret Beach Solutions

#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at

 #   http://www.apache.org/licenses/LICENSE-2.0

#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License."

source $SB_HOME/alp

color() { 
- color Changed the color in the shell or web version
- color Possible colors are white,bold,underline,error,red,green,yellow,blue,purple,aqua

	if [ -n $1 ]
	then
    case $1 in
        white)
            FG='00m'
        ;;
        bold)
            FG='01m'
        ;;
        underline)
            FG='04m'
        ;;
        error)
            FG='31m'
        ;;
        red)
            FG='31m'
        ;;
        green)
            FG='32m'
        ;;
        yellow)
            FG='33m'
        ;;
        blue)
            FG='34m'
        ;;
        purple)
            FG='35m'
        ;;
        aqua)
            FG='36m'
  			;;
    esac;

#    echo -n -e
     printf "\033[$FG"
	else 
		sb.help color
	fi

}

color.no() {

printf "\033[$1m"

}

alp color white bold underline error red green yellow blue purple aqua
alp color.no 31 32 33 34 35 36 37 38 39 40
alias red='color.no.31'
alias green='color.no.32'
alias blue='color.no.34'

source ~/.sbshell/color.ini
