#!/bin/bash

export SBSRV="john@purple"
export SBPATH="/home/john/public_html/sbshell"
export SBNOTE
export SBPAGE="1"
export SBSECTION="01"
export SBCONSOLE="ubu"
export SBCMDS
export SBDIR
export SBDSH=~/$$.dsh
export SBDSHDIR=~/dev/python/DSH
export SBRCMDS="$SBPATH/sbshell/sbshell-rcmds"
export SBVER="03152016"
umask 000

BASE="sbcs sbenv sbfont sbnote sbrenv sbset sbpre sbdiv sbvi"

EXT="sbprep sbls sbcat sbcp"

sb_cfg() {
env | grep "SB"
}

sb_sed() {
##sb_sed edit shell

vi $SBPATH/sbshell/
. $SBPATH/sbshell

}

sb_git() {
##sb_git git add,commit,push

git add .
git commit .
git push
}

function sbpurge { 
	rm sbshell.lib 
	}

function sbaddfun {

LIST=""

for SBFUN in $1
        do
        LIST="$LIST $SBPATH/sbshell/sbshell-lib/$SBFUN.fun"
	echo "Adding $SBFUN"
        done

ssh $SBSRV "cat $LIST" >> sbshell.lib

}

if [[ ! -e sbshell.lib ]]
	then
	  sbaddfun "$BASE"
	  sbaddfun "$EXT"
	fi

. sbshell.lib
