: version_5.0 pre-merge
export _SBCOLOR=red;
: Set your directory path here or specify with
: ./install.bash /usr/local/shells/examples/sbshell
export _SBDIR=~/sbshell;

cd ~/sbshell
git pull
git checkout version_5.0

#. $_SBDIR/lib/_sb/shell.bash

#_sb.shell

sbshell() {

: Verify that _SBDIR is the correct path 


_SBDIR=~/sbshell
. $_SBDIR/lib/_sb/shell.bash

_sb.shell

}

echo >> ~/.bashrc
declare -f sbshell >> ~/.bashrc

vi ~/.bashrc

sbshell
