#!/bin/bash

.web() {
declare -f | grep --color=none "^web." | sed 's/()//g'
}

web() {
web.set $1
}

web.env() {
env | grep --color=none "WEB_"

}

web.set() {
WEB_HOME=$1
PS1="web> "

}

web.pre() {

if [[ "$1" ]]
  then
  sb.font green
  script $WEB_HOME/$1_$2.php
  sb.font white
fi

}

web.vi.index() {

vi $WEB_LOCAL_URL/index.php

}

web.push.index() {

web.env

}


web.ssh() {
ssh rigler@rigler.org $1
}

. ~/.sbshell/web.ini

echo "reload web..."
