#!/bin/bash

. $SB_HOME/web

color.aqua
echo "Reload svg..."
color.blue

svg.git() {

git clone https://github.com/johnrigler/svg

}

svg.home() {

cd $WEB_LOCAL_URL

}

svg.push() {

scp $1 rigler@rigler.org:public_html/svg/.

}

svg.vi() {

vi $WEB_LOCAL_URL/svg/svg_lib.php
}

svg.rect.rounded() {

echo '<svg:path d="M0,0 L0,27 A3,3 0 0,0 3,30 L7,30 A3,3 0 0,0 10,27 L10,0 Z" />'

}

svg.header.lasersaur() {

- minimum header

cat << EOF
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="1251pt" height="446pt" viewBox="0 0 1251 446" version="1.1" xmlns="http://www.w3.org/2000/svg">
EOF

}

svg.circle.group.example() {

cat << EOF
<g id="#deadbeef">
<circle cx='100' cy='123' r='23' stroke='black'  stroke-width='4' />
</g>
EOF

}
